package slime.media;

public enum PlayState {IDLE, INITIALIZED, READY, PLAYING, PAUSED, STOPPED, FINISHED, END_OF_PLAYLIST, SKIPPED_FORWARDS, SKIPPED_BACK, SHUFFLE_TOGGLED, REPEAT_TOGGLED, SHUTDOWN, EXIT }
